version: '2'

services:
 nginx:
  ports:
   - "80:80"
  external_links:
   - "php"
   - "mysql"
  volumes:
   - "/www:/www" 
   - "/docker/compose/dudu/nginx/nginx.conf:/etc/nginx/nginx.conf"
   - "/docker/compose/dudu/nginx/logs:/etc/nginx/logs"
   - "/docker/compose/dudu/nginx/conf.d:/etc/nginx/conf.d"
  container_name: "nginx"
  depends_on:
    - "php"
    - "mysql"
  image: "nginx"
  restart: "always"
  extra_hosts: 
    - "centos:172.20.0.1"
  networks: 
    appnet:
      ipv4_address: "172.20.0.5"

 php:
  ports:
   - "9000:9000"
  external_links:
   - "mysql"
   - "redis"
  volumes:
   - "/www:/www"
   - "/docker/compose/dudu/php-fpm/7.1.15/conf.d:/usr/local/etc/php/conf.d"
   - "/docker/compose/dudu/php-fpm/7.1.15/logs:/logs"
  container_name: "php"
  image: "php-fpm:7.1.15-pdomysql"
  restart: "always"
  networks: 
    appnet:
      ipv4_address: "172.20.0.4"

 redis:
  ports:
   - "6379:6379"
  volumes:
   - "/docker/compose/dudu/redis/data:/data"
   - "/docker/compose/dudu/redis/redis.conf:/usr/local/etc/redis/redis.conf"
  container_name: "redis"
  image: "redis:4.0"
  restart: "always"
  command: redis-server /usr/local/etc/redis/redis.conf 
  networks:
    appnet: 
     ipv4_address: "172.20.0.3"

 mysql:
  ports:
   - "3306:3306"
  volumes:
   - "/www:/www"
   - "/docker/compose/dudu/mysql/5.6/data:/var/lib/mysql"
   - "/docker/compose/dudu/mysql/5.6/conf.d:/etc/mysql/conf.d"
  environment:
   MYSQL_ROOT_PASSWORD: "root"
  container_name: "mysql"
  image: "mysql:5.6"
  restart: "always"
  networks: 
    appnet:
      ipv4_address: "172.20.0.2"

networks:
  appnet:
    driver: "bridge"
    ipam: 
     driver: "default"
     config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1                   
                                       
