version: '2'

services:
 nginx:
  ports:
   - "80:80"
   - "443:443"
  external_links:
   - "php70"
   - "php71"
   - "php72"
   - "mysql55"
   - "mysql57"
  volumes:
   - "/www:/www" 
   - "${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf"
   - "${PWD}/nginx/logs:/etc/nginx/logs"
   - "${PWD}/nginx/conf.d:/etc/nginx/conf.d"
  container_name: "nginx"
  depends_on:
   - "php72"
   - "php71"
   - "php70"
   - "mysql57"
   - "mysql55"
  image: "nginx"
  restart: "always"
 
 php72:
  ports:
   - "9002:9000"
  external_links:
   - "mysql57"
   - "mysql55"
   - "redis"
  volumes:
   - "/www:/www"
   - "${PWD}/php-fpm/7.2.8/logs:/logs"
  container_name: "php72"
  image: "registry.cn-hangzhou.aliyuncs.com/listen/php-fpm-7.2.8"
  restart: "always"

 php71:
  ports:
   - "9001:9000"
  external_links:
   - "mysql57"
   - "mysql55"
   - "redis"
  volumes:
   - "/www:/www"
   - "${PWD}/php-fpm/7.1.15/logs:/logs"
  container_name: "php71"
  image: "registry.cn-hangzhou.aliyuncs.com/listen/php-fpm-7.1.15"
  restart: "always"

 php70:
   ports:
    - "9000:9000"
   external_links:
    - "mysql57"
    - "mysql55"
    - "redis"
   volumes:
    - "/www:/www"
    - "${PWD}/php-fpm/7.0.27/conf.d:/usr/local/etc/php/conf.d"
    - "${PWD}/php-fpm/7.0.27/logs:/logs"
   container_name: "php70"
   image: "registry.cn-hangzhou.aliyuncs.com/listen/php-fpm-7.0.27"
   restart: "always"

 redis:
  ports:
   - "6379:6379"
  volumes:
   - "${PWD}/redis/data:/data"
   - "${PWD}/redis/redis.conf:/usr/local/etc/redis/redis.conf"
  container_name: "redis"
  image: "redis:4.0"
  restart: "always"
  command: redis-server /usr/local/etc/redis/redis.conf 

 mysql57:
  ports:
   - "3306:3306"
  volumes:
   - "/www:/www"
   - "${PWD}/mysql/5.7/data:/var/lib/mysql"
   - "${PWD}/mysql/5.7/conf.d:/etc/mysql/conf.d"
  environment:
   MYSQL_ROOT_PASSWORD: "root"
  container_name: "mysql57"
  image: "mysql:5.7.20"
  restart: "always"
 
 mysql55:
  ports:
   - "3307:3306"
  volumes:
   - "/www:/www"
   - "${PWD}/mysql/5.5.58/data:/var/lib/mysql"
   - "${PWD}/mysql/5.5.58/conf.d:/etc/mysql/conf.d"
  environment:
   MYSQL_ROOT_PASSWORD: "root"
  container_name: "mysql55"
  image: "mysql:5.5.58"
  restart: "always"
