version: '2'

services:
 nginx:
  ports:
   - "80:80"
  external_links:
   - "php"
   - "mysql"
   - "redis"
  volumes:
   - "/www:/www" 
   - "$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf"
   - "$PWD/nginx/logs:/etc/nginx/logs"
   - "$PWD/nginx/conf.d:/etc/nginx/conf.d"
  container_name: "nginx"
  depends_on:
    - "php"
    - "mysql"
    - "redis"
  image: "nginx"
  restart: "always"
  extra_hosts: 
    - "centos:172.19.0.1"
  networks: 
    appnet:
      ipv4_address: "172.19.0.5"

 php:
  ports:
   - "9000:9000"
  external_links:
   - "mysql"
   - "redis"
  volumes:
   - "/www:/www"
   - "${PWD}/php-fpm/7.0.27/conf.d:/usr/local/etc/php/conf.d"
   - "${PWD}/php-fpm/7.0.27/logs:/logs"
  container_name: "php"
  image: "registry.cn-hangzhou.aliyuncs.com/listen/php-fpm-7.0.27"
  restart: "always"
  networks: 
    appnet:
      ipv4_address: "172.19.0.4"

 mysql:
  ports:
   - "3306:3306"
  volumes:
   - "/www:/www"
   - "${PWD}/mysql/5.5.58/data:/var/lib/mysql"
   - "${PWD}/mysql/5.5.58/conf.d:/etc/mysql/conf.d"
  environment:
   MYSQL_ROOT_PASSWORD: "root"
  container_name: "mysql"
  image: "mysql:5.5.58"
  restart: "always"
  networks: 
    appnet:
      ipv4_address: "172.19.0.2"

 redis:
  ports:
   - "6379:6379"
  volumes:
   - "${PWD}/redis/data:/data"
   - "${PWD}/redis/redis.conf:/usr/local/etc/redis/redis.conf"
  container_name: "redis"
  image: "redis:3.2"
  restart: "always"
  command: redis-server /usr/local/etc/redis/redis.conf 
  networks: 
    appnet:
      ipv4_address: "172.19.0.3"

networks:
  appnet:
    driver: "bridge"
    ipam: 
     driver: "default"
     config:
      - subnet: 172.19.0.0/24
        gateway: 172.19.0.1                   
                                       
