version: '2.0'

services:
  elasticsearch:
    volumes:
      - "/docker/lnmp/compose/search/esdata:/usr/share/elasticsearch/data"
    container_name: "es"  
    image: elasticsearch:5.6.3
    #entrypoint:
    #  - elasticsearch 
    #  - -Etransport.host=0.0.0.0
    #  - -Ediscovery.zen.minimum_master_nodes=1
    ports: 
      - 9200:9200
    networks: 
      appnet:
        ipv4_address: "172.18.0.7"

  kibana:
    image: kibana:5.6.3
    container_name: "kibana"
    ports:
      - 5601:5601
    networks: 
      appnet:
        ipv4_address: "172.18.0.8"    

networks:
  appnet:
    driver: "bridge"
    ipam: 
      driver: "default"
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1    
